version: '3'

volumes:
  CI_postgres_data: {}
  CI_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/CI/django/Dockerfile
    image: timberframes_CI_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/CI/postgres/Dockerfile
    image: timberframes_CI_postgres
    container_name: postgres
    volumes:
      - CI_postgres_data:/var/lib/postgresql/data:Z
      - CI_postgres_data_backups:/backups:z
    env_file:
      - .env

  docs:
    image: timberframes_CI_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/CI/docs/Dockerfile
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./timberframes:/app/timberframes:z
    ports:
      - "7000:7000"
    command: /start-docs
