# Generated by Django 3.2.9 on 2022-12-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wood_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wood_name", models.CharField(max_length=200)),
                (
                    "lumber_type",
                    models.CharField(
                        choices=[
                            ("lumber", "Cut Lumber"),
                            ("glulam", "Glulam"),
                            ("log", "Raw Log"),
                        ],
                        default="lumber",
                        max_length=20,
                        verbose_name="Lumber Type",
                    ),
                ),
                (
                    "lumber_grade",
                    models.CharField(
                        choices=[
                            ("select_structural", "Select Structural"),
                            ("no_1", "No. 1"),
                            ("no_2", "No. 2"),
                            ("no_3", "No. 3"),
                            ("stud", "Stud"),
                        ],
                        default="no_2",
                        max_length=20,
                        verbose_name="Lumber Grade",
                    ),
                ),
                (
                    "E",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Modulus of Elasticity (psi)",
                    ),
                ),
                (
                    "E_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Minimum Modulus of Elasticity (psi)",
                    ),
                ),
                (
                    "G",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Specific Gravity"
                    ),
                ),
                (
                    "F_v",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Design Shear Parallel to Grain (psi)",
                    ),
                ),
                (
                    "F_c",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Design Compression Parallel to Grain (psi)",
                    ),
                ),
                (
                    "F_c_perp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Design Compression Perperdicular to Grain (psi)",
                    ),
                ),
                (
                    "F_b",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Design Bending (psi)",
                    ),
                ),
                (
                    "F_t",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Design Tension Parallel to Grain (psi)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wood Type",
                "verbose_name_plural": "Wood Types",
            },
        ),
        migrations.CreateModel(
            name="Beams_and_Columns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_selected_support_type",
                    models.CharField(
                        choices=[
                            ("beam", "Beam"),
                            ("column", "Column"),
                            ("beam_and_column", "Combination of Beam and Column"),
                        ],
                        default="beam",
                        max_length=30,
                        verbose_name="Support Type",
                    ),
                ),
                (
                    "breadth",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=6,
                        verbose_name="Breadth of beam/column",
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=6,
                        verbose_name="Depth of beam/column",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=6,
                        verbose_name="Unsupported span length (vertical or horizontal)",
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beams_and_columns.wood_type",
                        verbose_name="Wood Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beam and Column Calculation",
                "verbose_name_plural": "Beam and Column Calculations",
            },
        ),
    ]
