# Generated by Django 3.2.9 on 2021-12-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beams_and_columns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lumber_Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lumber_Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lumber_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wood_Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breadth", models.DecimalField(decimal_places=2, max_digits=5)),
                ("depth", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Wood_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wood_name", models.CharField(max_length=200)),
                ("E", models.DecimalField(decimal_places=2, max_digits=7)),
                ("E_min", models.DecimalField(decimal_places=2, max_digits=7)),
                ("G", models.DecimalField(decimal_places=2, max_digits=7)),
                ("F_v", models.DecimalField(decimal_places=2, max_digits=7)),
                ("F_c", models.DecimalField(decimal_places=2, max_digits=7)),
                ("F_c_perp", models.DecimalField(decimal_places=2, max_digits=7)),
                ("F_b", models.DecimalField(decimal_places=2, max_digits=7)),
                ("F_t", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="wood_choice",
            name="wood_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="beams_and_columns.wood_type",
            ),
        ),
    ]
